### ISSUE TITLE
Boolean value matching in JSONPath when finding don't seem to work

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Icarus#3]
When searching for objects in a JSON file via JSONPath by a boolean value, an error is thrown by Icarus.

**Comment by Badgerati** [comment]
Appears to be that if you specify `$[?(@.SomeBool == true)]` directly it works, however `$[?(@.SomeBool == " + value + ")]` fails with:

```
Newtonsoft.Json.JsonException : Could not read query value.
    IcarusCollection.cs(335,0): at Icarus.Core.IcarusCollection`1.Find(String jsonPath)
    BasicTests.cs(293,0): at Icarus.Test.BasicTests.Find_JsonPath_Boolean_Success(Boolean value)
    --JsonException
    at Newtonsoft.Json.Linq.JsonPath.JPath.ParseValue()
    at Newtonsoft.Json.Linq.JsonPath.JPath.ParseExpression()
    at Newtonsoft.Json.Linq.JsonPath.JPath.ParseQuery(Char indexerCloseChar)
    at Newtonsoft.Json.Linq.JsonPath.JPath.ParseIndexer(Char indexerOpenChar)
    at Newtonsoft.Json.Linq.JsonPath.JPath.ParsePath(List`1 filters, Int32 currentPartStartIndex, Boolean query)
    at Newtonsoft.Json.Linq.JsonPath.JPath.ParseMain()
    at Newtonsoft.Json.Linq.JsonPath.JPath..ctor(String expression)
    at Newtonsoft.Json.Linq.JToken.SelectToken(String path, Boolean errorWhenNoMatch)
    at Newtonsoft.Json.Linq.JToken.SelectToken(String path)
    IcarusCollection.cs(713,0): at Icarus.Core.IcarusCollection`1.GetTokenByJsonPath(String jsonPath)
    IcarusCollection.cs(317,0): at Icarus.Core.IcarusCollection`1.Find(String jsonPath)
```

**Comment by Badgerati** [comment]
Oh wow, the latter format actually generates a JSONPath of `$[?(@.SomeBool == True)]` which fails, note the capital 'T' on True.

**Comment by Badgerati** [comment]
For direct JSONPath searches this is something that'll have to be left to the user to debug. For searches done by using Icarus' filter overload, the boolean value is automatically lowercased.
